import type { Prisma } from '../generated/prisma/client.js';

// A small, hand-picked spread across item types and statuses so a visitor
// immediately sees what the app can hold — not a copy of the production
// seed data, just enough variety to explore sorting/filtering/inline edits.
export const DEMO_LOCATIONS: Omit<Prisma.LocationCreateManyInput, 'userId'>[] = [
  { name: 'Living room shelf' },
  { name: 'Office' },
];

export const DEMO_BOOKS: Omit<Prisma.BookCreateManyInput, 'userId' | 'locationId'>[] = [
  {
    title: 'Dune',
    author: 'Frank Herbert',
    itemType: 'book',
    category: 'Sci-fi',
    subcategory: 'Space opera',
    format: 'paperback',
    ownershipFormat: 'physical',
    libraryStatus: 'owned',
    readingStatus: 'read',
    isFavorite: true,
    myNote: 9,
    myReview: 'A classic for a reason.',
  },
  {
    title: 'Clean Code',
    author: 'Robert C. Martin',
    itemType: 'book',
    category: 'Programming',
    subcategory: 'Software craftsmanship',
    format: 'ebook',
    ownershipFormat: 'digital',
    libraryStatus: 'owned',
    readingStatus: 'reading',
    myNote: 7,
  },
  {
    title: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    itemType: 'book',
    category: 'Fantasy',
    format: 'hardcover',
    ownershipFormat: 'physical',
    libraryStatus: 'owned',
    readingStatus: 'unread',
  },
  {
    title: 'One Piece #105',
    author: 'Eiichiro Oda',
    itemType: 'manga',
    category: 'Manga',
    subcategory: 'Shonen',
    seriesName: 'One Piece',
    seriesNumber: '105',
    format: 'paperback',
    ownershipFormat: 'physical',
    libraryStatus: 'owned',
    readingStatus: 'reading',
    isFavorite: true,
  },
  {
    title: 'Death Note #3',
    author: 'Tsugumi Ohba',
    itemType: 'manga',
    category: 'Manga',
    subcategory: 'Mystery',
    seriesName: 'Death Note',
    seriesNumber: '3',
    format: 'paperback',
    ownershipFormat: 'physical',
    libraryStatus: 'owned',
    readingStatus: 'read',
  },
  {
    title: 'National Geographic — March 2024',
    author: 'National Geographic Society',
    itemType: 'magazine',
    category: 'Science',
    seriesName: 'National Geographic',
    seriesNumber: 'March 2024',
    format: 'magazine',
    ownershipFormat: 'physical',
    libraryStatus: 'owned',
    readingStatus: 'unread',
  },
  {
    title: 'XIII #1',
    author: 'Jean Van Hamme',
    itemType: 'bd',
    category: 'Bande dessinée',
    seriesName: 'XIII',
    seriesNumber: '1',
    format: 'hardcover',
    ownershipFormat: 'physical',
    libraryStatus: 'owned',
    readingStatus: 'read',
  },
  {
    title: 'Solo Leveling #4',
    author: 'Chugong',
    itemType: 'manhwa',
    category: 'Manhwa',
    subcategory: 'Fantasy',
    seriesName: 'Solo Leveling',
    seriesNumber: '4',
    format: 'ebook',
    ownershipFormat: 'digital',
    libraryStatus: 'owned',
    readingStatus: 'reading',
  },
  {
    title: 'Atomic Habits',
    author: 'James Clear',
    itemType: 'book',
    category: 'Self-help',
    format: 'ebook',
    ownershipFormat: 'digital',
    libraryStatus: 'wishlist',
    readingStatus: 'unread',
  },
  {
    title: 'Project Hail Mary',
    author: 'Andy Weir',
    itemType: 'book',
    category: 'Sci-fi',
    format: 'hardcover',
    ownershipFormat: 'physical',
    libraryStatus: 'owned',
    readingStatus: 'abandoned',
    myNote: 6,
  },
];
